tunnel: a1301e8f-4bcd-4a14-8ead-8ab181fddf9f
token: eyJhIjoiZTAzNTliMTAzMDIyZDZkNWNiOTdlMTkyNzE5ZGExYjciLCJ0IjoiYTEzMDFlOGYtNGJjZC00YTE0LThlYWQtOGFiMTgxZmRkZjlmIiwicyI6Ik1UVTVNRGMzWmpNdFlUVTFOQzAwWlRNNUxXRTJPREV0WTJNeVpEVTJPVEV3WVRRdyJ9

ingress:
  # Route portfolio.joaquinpacia.com to the portfolio container
  - hostname: portfolio.joaquinpacia.com
    service: http://192.168.2.39:80

  # Keep existing service for affine.joaquinpacia.com
  - hostname: affine.joaquinpacia.com
    service: http://192.168.2.39:3010

  # You can add more services as needed by following this pattern:
  # - hostname: another-service.joaquinpacia.com
  #   service: http://another-service:port

  # Catch-all rule, which just responds with 404 if traffic doesn't match any other rule
  - service: http_status:404
