name: Deploy to Docker

on:
  push:
    branches: [ main, master ]  # Adjust branches as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/portfolio_deploy_key
          chmod 600 ~/.ssh/portfolio_deploy_key
          echo -e "Host tunnel\n\tHostName ${{ secrets.SSH_HOST }}\n\tUser ${{ secrets.SSH_USER }}\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config

      - name: Deploy to Server
        run: |
          # Connect via SSH through Cloudflare Tunnel and execute deployment script
          ssh tunnel 'bash -s' << 'EOF'
            cd ${{ secrets.SERVER_DEPLOY_PATH }}

            # Pull latest code
            git pull

            # Build or rebuild the Docker container
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d

            # Optional: Remove unused Docker resources
            docker system prune -f

            echo "Deployment completed successfully!"
          EOF